# Generated by Django 3.1.8 on 2021-04-26 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.IntegerField(unique=True)),
                ('person_name', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_onset', models.DateField()),
                ('date_of_confirmation', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100)),
                ('venue_location', models.CharField(max_length=1000)),
                ('venue_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('venue_x_coord', models.IntegerField(blank=True, null=True)),
                ('venue_y_coord', models.IntegerField(blank=True, null=True)),
                ('date_of_event', models.DateField()),
                ('description', models.CharField(max_length=3000)),
                ('infector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.infector')),
            ],
        ),
    ]
