# Generated by Django 3.1.8 on 2021-04-26 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='infector',
        ),
        migrations.AddField(
            model_name='event',
            name='is_SSE',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=3000)),
                ('is_infector', models.BooleanField()),
                ('is_infected', models.BooleanField()),
                ('event_attended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.event')),
                ('infector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.infector')),
            ],
        ),
    ]
