# Generated by Django 3.2 on 2021-04-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_auto_20210425_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_x_coord',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_y_coord',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
