# Generated by Django 3.1.5 on 2021-04-20 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseNumber', models.IntegerField()),
                ('personName', models.CharField(max_length=200)),
                ('idNumber', models.CharField(max_length=200)),
                ('dateOfBirth', models.DateField()),
                ('dateOfOnset', models.DateField()),
                ('dateCaseConfirmed', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venueName', models.CharField(max_length=200)),
                ('venueLocation', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
                ('dateOfEvent', models.DateField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
    ]
